@extends('layouts.bank-layout')
@section('title', 'Bank Payment')

@section('content')
    <div class="container mt-5">
        <h2 class="text-center text-primary">Transfer</h2>
        <!-- Payment Types Catalog -->
        <div class="mb-3">
            <label class="form-label text-info font-weight-bold">Choose Trasnfer Method</label>
            <div class="row">
                <!-- Antar Rekening BCA -->
                <div class="col-md-4 mb-3">
                    <div class="card h-100 shadow-sm">
                        <div class="card-header bg-primary text-white">
                            <i class="fas fa-university me-2"></i>
                            <strong>Antar Rekening BCA</strong>
                        </div>
                        <div class="card-body text-center">
                            <p>Transfer uang ke rekening BCA lain secara cepat dan aman.</p>
                            <button type="radio" name="payment_method" value="antar_rekening_bca"
                                class="btn btn-outline-primary">
                                Select
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Antar Bank -->
                <div class="col-md-4 mb-3">
                    <div class="card h-100 shadow-sm">
                        <div class="card-header bg-success text-white">
                            <i class="fas fa-exchange-alt me-2"></i>
                            <strong>Antar Bank</strong>
                        </div>
                        <div class="card-body text-center">
                            <p>Transfer uang ke rekening bank lain di Indonesia.</p>
                            <button type="radio" name="payment_method" value="antar_bank"
                                class="btn btn-outline-success">
                                Select
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Transfer ke Sakuku -->
                <div class="col-md-4 mb-3">
                    <div class="card h-100 shadow-sm">
                        <div class="card-header bg-info text-white">
                            <i class="fas fa-wallet me-2"></i>
                            <strong>Transfer ke Sakuku</strong>
                        </div>
                        <div class="card-body text-center">
                            <p>Kirim uang langsung ke dompet digital Sakuku.</p>
                            <button type="radio" name="payment_method" value="transfer_sakuku"
                                class="btn btn-outline-info">
                                Select
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Transfer Valas -->
                <div class="col-md-4 mb-3">
                    <div class="card h-100 shadow-sm">
                        <div class="card-header bg-warning text-white">
                            <i class="fas fa-globe me-2"></i>
                            <strong>Transfer Valas</strong>
                        </div>
                        <div class="card-body text-center">
                            <p>Transfer uang ke rekening luar negeri dengan valuta asing.</p>
                            <button type="radio" name="payment_method" value="transfer_valas"
                                class="btn btn-outline-warning">
                                Select
                            </button>
                        </div>
                    </div>
                </div>

                <!-- BCA Virtual Account -->
                <div class="col-md-4 mb-3">
                    <div class="card h-100 shadow-sm">
                        <div class="card-header bg-dark text-white">
                            <i class="fas fa-credit-card me-2"></i>
                            <strong>BCA Virtual Account</strong>
                        </div>
                        <div class="card-body text-center">
                            <p>Pay through a unique Virtual Account number generated by BCA.</p>
                            <a href="/bank/payment/virtual" class="btn btn-outline-dark">
                                Select
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
